project:
  type: book

book:
  title: "Le rôle des divinités dans les *Métamorphoses* d’Ovide : étude des cas de Minerve, Apollon et Jupiter"
  author: "Axelle Penture"
  date: 07-07-2025
  chapters:
    - index.qmd
    - introduction.qmd
    - partie1.qmd
    - partie2.qmd
    - partie3.qmd
    - conclusion.qmd
    - annexe_readmd_github.qmd
    - annexe_tab_data_plus.qmd
    - loft.qmd
    - bibliographie.qmd

csl: chicago-annotated-bibliography.csl 
execute:
  freeze: auto
  
bibliography: ./bibliographie/bib_memoire_m2_v5.bib

format:
  html:
    number_sections: true
    toc: true
    comments:
      hypothesis: true
    css: styles.css
  docx: default
  jats: default
  agu-pdf: default
  pdf:
    toc: true
    lof: false
    lot: false
    number-sections: false
    latex-engine: xelatex
    colorlinks: true
    documentclass: report
    geometry: top=3cm, bottom=3cm, left=3cm, right=2.5cm
    title: ""
    include-before-body: titlepage.tex
    include-in-header:
      text: |
        \usepackage{ragged2e}
        \setlength{\emergencystretch}{3em}
        \raggedbottom
        \raggedright
    number_sections: true
    fig-caption: true
    fig-pos: 'H'
    fig-align: center
    echo: false
    fig-cap-location: bottom
    