project:
  type: book

book:
  title: "Le rôle des divinités dans les *Métamorphoses* d’Ovide : étude des cas de Minerve, Apollon et Jupiter"
  author: "Axelle Penture"
  date: 03-07-2025
  chapters:
    - index.qmd
    - partie1.qmd
    - partie2.qmd
    - partie3.qmd
    - conclusion.qmd

csl: chicago-annotated-bibliography.csl # ou autre à voir dans le dépôt GitHub
execute:
  freeze: auto

format:
  html:
    toc: true
    comments:
      hypothesis: true
    css: styles.css
  docx: default
  jats: default
  agu-pdf: default
  pdf:
    toc: true
    number-sections: true
    latex-engine: xelatex
    include-in-header:
      text: |
        \usepackage{ragged2e}
        \setlength{\emergencystretch}{3em}
        \raggedbottom
        \raggedright
