---
title: "Introduction"
format: pdf
bibliography: ./bibliographie/bib_memoire_m2_v5.bib
---

> « La métamorphose est d’abord le pouvoir de métamorphoser que détiennent les divinités. » [@delbey_pouvoir_2011]

Dans son article intitulé « Pouvoir de la métamorphose et métamorphose du pouvoir dans le Livre XIV des *Métamorphoses* d’Ovide », Évrad Delbey, docteur ès lettres et professeur à l'université Paris-4 souligne cette évidence : dans les *Métamorphoses,* les divinités ont le monopole du processus de métamorphose. D'abord sur elles-mêmes, puisqu'elles revêtent des formes qui vont de l'humain à l'animal en passant par les éléments naturels, à l'instar de Thétis lorsqu'elle tente d'échapper à Pelée au livre XI. Mais surtout, sur les mortels; ainsi les *Métamorphoses* voient s'enchaîner les récits de transformations de mortels en divers animaux ou végétaux, entre les châtiments et les actes de compassion des divinités qui s'engagent dans des interactions avec eux.

Le corpus des *Métamorphoses* d'Ovide est connu pour sa densité. Les 11 992 vers ont traversés divers assemblages, et ont été le support d'analyse, d'interprétations et de critiques ciblées, inégalement concentrées sur des épisodes et des représentations particulières. Mon choix de travailler sur l'ensemble des quinze livre est motivé par plusieurs raisons pratiques et méthodologiques. Dans un premier temps, il s'agissait pour moi de poursuivre mon précédent travail, qui visait à mettre à jour à travers une approche numérique des éléments structurants aux différentes échelles sur l'ensemble des livres. Je m'appuyais principalement pour cela sur le travail de thèse de Gilles @tronchet_metamorphose_1997, intitulé *La métamorphose à l'œuvre : recherches sur la poétique d'Ovide dans les "Métamorphoses"*, travail dans lequel il explore en profondeur la poétique d'Ovide et souligne les indices des divers niveaux de structure à travers elle. Mon premier travail consistait donc en une exploration numérique de ce corpus à partir des catégories créées par Gilles Tronchet, qui suivait une logique narrative rigoureuse. Ces données, dont les catégories sont organisées dans deux tableaux distincts, sont disponibles en format `xslt` en ligne [ici](#0). À travers ce premier travail de recherche, j'ai pu me familiariser avec le processus d'exploration numérique et aborder ce texte d'Ovide avec une approche à la fois numérique et littéraire.

Dans le présent travail, je cherche à affiner ces deux approches à partir de mon expérience précédente. L'angle de la structure, très vaste et avec de nombreux points d'entres et de niveaux à explorer, est une question qui n'a de cesse d'ouvrir des chemins d'interprétation pour ce texte. Je décide de l'aborder à travers l'angle des divinités. Les analyses des épisodes des *Métamorphoses* recherchent principalement et généralement la symbolique de la transformation. Tout comme Gilles Tronchet et bien d'autres avant lui comme après lui, il s'agit surtout de catégoriser la métamorphose, de définir ce qu'elle signifie et quelle symbolique peut-on y lire. Les divinités sont souvent simplement mentionnées comme *media* de la métamorphose, avec la cause générale qui les conduit à en provoquer une : généralement colère, passion, ou pitié. Les divinités sont des personnalités au coeur des épisodes : Jupiter ouvre le déroulé des récits et tient une place centrale dans les épisodes très connus de la transformation de Lycaon, l'enlèvement d'Europe ou encore le priple d'Io; Apollon n'est pas en reste avec ses amours pour Hyacinthe et Daphné ainsi que la mort de son fils Phaéton, sur le char du Soleil; quant à Minerve, ses plus célbres épisodes restent sa vengeance sur Arachné et son rôle dans les périples de Persée contre Méduse. \
\
Ces trois divinités sont nommées ici car sont les trois fils rouges qui sont tirés pour dérouler cette étude. Le premier choix s'est porté sur Minerve en raison d'une inclination personnlle marqué à son égard, mais aussi car son nombre d'occurrences total dans le texte semblait abordable pour le travail préparatoire. Cependant, avec les premières manipulations des données, la nécessité de plusieurs divinités, et de divinités avec une présence narrative davanatge conséquente, s'est fait ressentir. Le choix s'est naturellement arrêté sur Jupiter, en maître des dieux, dont il était certain mêem sans regarder les chiffre d'une omniprésence narrative. L'analyse quantitative confirme cette domination dans le texte, qui offre de la matière à l'interprétation croisée que j'ai tenté d'articuler ici. Quant à Apollon, la lecture cursive du texte le voyait revenir de façon assez récurrente pour intriguer et pousser à une analyse comparée avec les deux autres.

L'approche en question cherche à proposer une lecture à la fois quantitative et qualitative, à la fois numérique et littéraire du texte. L'approche numérique ne suit pas une suite logique fixe et déterminée, mais plutôt une logique de va-et-vient entre macrolecture et microlecture. Cela se réalise d'abord du point de vue des données, à travers les différents algorithmes mis en place pour explorer la base de données issue du travail préparatoire. Puis, lorsque les moments charnières pertinents pour la présente analyse sont dégagés, un regard littéraire et critique décortique les moments choisis. Bien entendu, ce regard sur le texte ne disparait pas lors des traitements numériques, et éclaire le texte et les données qui en sont tirées à la lueur de sa connaissance préalable. Une des finalités de cette démarche est la création d'une édition numérique qui autorise une exploration personnelle du texte, à travers l'outil [EVT](https://github.com/evt-project/evt-viewer-angular/wiki), un outil de publication numérique *open-source* dont les paramètres sont présentés en première partie.

Le travail préparatoire a consisté en deux phases. Tout d'abord un encodage éclairé du texte, dont les détails du choix des mentions, des balises et des attributs sélectionnés sont développés dans la première partie. Les travaux numériques précédents se sont révélés une base très solide pour le départ de cette recherche. L'encodage lui-même ne s'est pas réalisé sans l'appui d'éditions physique du texte, et a nécessité dès cette étape la mobilisation de méthodes littéraires classiques. Une fois cet encodage terminé, la deuxième phase est celle de la conception des outils d'analyse, ou plus précisement, de l'extraction des données et de la création des algorithmes pour les manipuler mais surtout les visualiser de façon pertinente. Lors de cette étape, les divinités sont toujours au centre, car ce sont les questions que l'on se pose autour d'elles qui indiquent à quelles questions doivent permettre de répondre les algorithmes. Les observations et les intuitions à l'échelle des quinze livre comme à l'échelle d'un seul m'ont conduit principalement vers des diagrammes en barres empilées, idéals pour des représentaitions proportionelles de données partant d'une base quantitative différentes mais qui cherchent à être mises en parallèle. Les représentations et les analyses suivent une structure commune qui s'intéresse au général puis au cas de chaque divinité par ordre alphabétique. D'autres visualisations, telles que les *heatmaps*, les bigrammes et les nuages de mots, apportent des informations supplémentaires sur les divinités aux moment opportuns.

Ainsi, le travail de recherche s'attache ici à éclairer deux questionnements : la mise en place des divinités choisies et de leurs facettes au service de la narration des *Métamrophoses*, mais également la construction de leur individualité en tant que personnages centraux de ces récits enchassés.

La recherche et l'application d'une méthode est aussi au centre du travail, ce qui fait de la première partie une vitrine des étapes préparatoires, des concepts mobilisés et des outils nécessaires à cette analyse textuelle numérique. Il s'agit d'établir les éléments qui ont permis la constitution du corpus, les méthodes qui ont guidé le travail, et de partir d'une base littéraire pour le portrait des divinités qui guide notre lecture. Ensuite, l'approche numérique présentera ses résultats, avec une analyse structurelle globale rythmée par des lectures de l'ensemble pour lui-même puis à travers chaque divinité concernée. Cette partie présente également des pistes d'analyses sur la présence narrative entre discours narratif et paroles rapportées, ainsi qu'une analyse lexicale qui ouvrent, avec les algorithmes respectifs qu'elles mobilisent, des points d'entrée pour une lecture des portraits plus détaillée. Ces portraits sont davantage explorés dans la troisième partie, grâce à une analyse littéraire d'épisodes choisis, appuyée par un algorithme de requêtes intéractif, qui permet de naviguer dans les données encodées de façon aisée et trouver ainsi les points de tensions selon ce qui est recherché dans le texte. Les portraits de divinités sont alors étoffés à la lumière de ces observations, avant de mener à une synthèse du travail effectué.
