---
title: "1. Fondations : corpus, méthodes et données"
author: "Axelle Penture"
editor: visual
bibliography: 
  - ./bibliographie/bib_memoire_m2_v5.bib
---

## 1.1. Constitution du corpus

### 1.1.1. Corpus manuscrit et numérique : travail de Nadine Rakofsky et dépassement

Avant de se plonger dans le corpus numérique, il faut évoquer brièvement les éditions tapuscrites physiques qui sont au cœur de la bibliographie, car le travail numérique que je réalise appelle une vérification progressive de l'encodage à partie d'une base de référence. . À la question du choix des éditions des *Métamorphoses*, je réponds donc avec les trois ouvrages de la collection des Belles Lettres publiés entre 1965 et 1966, dont le texte est établi par Georges Lafaye. Ils ont été ma référence de vérification pour l’encodage et mon support d’analyse littéraire pour le présent travail. Pour la traduction, je m'appuie principalement sur la sienne et sur celle de Marie Cosnay, qui publie une traduction en vers aux éditions de l'Ogre en 2O17.

En ce qui concerne le corpus numérique, support de l'analyse, il fallait dans l’idéal partir d’un fichier un peu plus élaboré qu’un fichier en *plain text*, avec un premier niveau d’encodage qui, *a minima*, distinguait les livres les uns des autres ainsi que les épisodes à l’intérieur de chaque livre. C’est le format de fichier proposé à l’exportation par la [Perseus Digital Library](https://www.perseus.tufts.edu/hopper/). Cependant, par l’intermédiaire d’Aurélien Berra, j’ai pu accéder au fichier de travail d’une ancienne élève du master, Nadine Rakofsky, qui a travaillé sur [le genre d’Iphis au livre IX des Métamorphoses](#0), ainsi que sur [la question du secret sur l’ensemble des quinze livres](#0). Son fichier prend pour point de départ celui de la Perseus Digital Library, qui propose à l’exportation tous ces textes en format XML. Le texte choisi pour l’encodage n’est pas celui établi par Georges Lafaye, mais celui d’Hugo Magnus qui publie le texte établi en 1892 en Allemagne, aux éditions Friedrich Andreas Perthes. L’édition présente un encodage de la structure simple, à savoir le découpage des livres et la séparation des épisodes narratifs au sein des livres. Nadine Rakofsky, dans le cadre de ses recherches, y a ajouté le balisage des personnages en tant que narrateur ou personnage à de l’action tout au long des quinze livres à travers une balise `<sp>`. Sa base de travail s’est avérée parfaite pour le présent travail, car son encodage permet une analyse de la prise de parole des divinités choisies. De plus, venir enrichir un fichier s’inscrit dans l’esprit de ma recherche qui, bien qu’elle s’intéresse uniquement à trois divinités ici, a pour perspective d’ouvrir ldes poisiblités d'analyse d’un ensemble plus exhaustif de divinités dans les *Métamorphoses*. Ce texte fait lui-même l’objet d’enrichissements antérieurs à celui de Nadine Rakofsky, en vue d’une amélioration contiunue de l’édition numérique proposée sur [Scaife Viewer](#0).

### 1.1.2. Identification et extraction des mentions divines : travail préparatoire d'encodage

Avant d’entrer dans le fichier et de modifier le cœur du texte, il me faut déterminer ce que je vais encoder et comment. Le choix des divinités a été présenté en introduction : je m’attache ici à expliquer quelles mentions de divinités sont encodées et sous quelle forme dois-je les encoder pour les appeler dans mes scripts `.R` depuis le fichier `.xml`.

Les mentions des divinités, dans un sens large, se déploient, comme celles des personnages, sur un spectre qui s'étend de la mention directe et explicite de leur nom propre, à celle plus subtile d’un pronom de rappel ou adjectif, dont le sens dépend du contexte dans lequel il est employé. Entre ces deux extrémités se situent diverses périphrases, fréquemment liées à la généalogie (par exemple « fils de Saturne »), ou bien mentionnant simplement la nature du personnage évoqué précédemment (comme « le dieu »). Cependant, les *Métamorphoses* sont une œuvre longue et très riche en personnages, avec environ 270 recensés dans l’*index nominum* de l’édition Budé. La longueur globale du récit et les enchâssements des épisodes appellent à une clarification constante pour être compris du lecteur, ce qui passe nécessairement par l’emploi relativment régulier de qualificatifs clairs quant aux personnages convoqués. Partant de cela et dans le souci pratique du cadre d’un travail de mémoire, j’ai donc fait le choix d’encoder uniquement les mentions de noms propres des divinités ainsi que les périphrases les désignants, récurrentes ou non. Les occurrences des noms propres, peu importe leur cas, sont déjà répertoriées par l’édition physique des *Métamorphoses*, dans l’*index nominum*. Les mentions des périphrases ont été relevées par la lecture suivie du texte, et ont fait l’objet d’une vérification par recherche de mots-clés dans le texte numérique après un premier encodage.

Pour ce qui est du balisage en lui-même, j’ai d’abord cherché à créer une nouvelle balise qui marquerait de façon explicite la recherche des divinités, sobrement intitulé `<deityRole>`. Cependant, le processus de création d’une balise est relativement long pour des résultats atteignables avec celles déjà existantes. Je me suis donc finalement tournée vers les possibilités offertes par la balise `<persName>`, qui propose un ensemble d’attributs tout à fait approprié pour mes identifications. Comme elle n’avait pas été utilisée par Nadine Rakofsky, son emploi simplifiait également mon script R pour l'analyse des données.

J’associe à cette balise trois attributs. Le premier attribut, `ref`, permet d’identifier la divinité dont il est question dans le passage. Les divinités sont identifiées par les trois premières lettres de leur nom latin : « MIN » pour Minerve, « APO » pour Apollon et « IUP » pour Jupiter. Il est aisé de poursuivre cette liste pour n’importe quelle autre divinité. Ensuite, l’attribut `type` qui, selon la définition des [TEI Guidelines](https://www.tei-c.org/release/doc/tei-p5-doc/fr/html/ref-persName.html), « caractérise l'élément en utilisant n'importe quel système ou typologie de classification approprié ». Il y a deux valeurs possibles pour cet attribut : soit le passage dans lequel la mention de la divinité apparaît correspond à un passage direct de métamorphose, tel qu’ils ont été établi dans [le découpage réalisé l’an dernier](https://docs.google.com/spreadsheets/d/1n_TWKsEPywmv3aVzptd-_cRNn-tIxXZQ3tHtt0w_TJE/edit?gid=2010180086#gid=2010180086). Les passages correspondants portent l’étiquette `metamorphosis`. Tous les autres passages sont par défaut des passages narratifs, donc étiquetés `narrative`. Enfin, l’attribut `ana` permet de faire la distinction du rôle tenu par la divinité dans l’action qui se joue autour. L’année précédente, le travail de thèse de Gilles Tronchet [@tronchet_metamorphose_1997] qui distinguait les épisodes par vers ainsi que les métamorphoses selon différentrs catgorisations, que j'ai retravaillé notamment avec la nomination et la délimitation des vers des acteurs, a permis de mettre en évidence les rôles des personnages impliqués des métamorphoses, distinguant les acteurs et les objets. Aussi, cet attribut peut accueillir quatre valeurs :

-   `act`, qui désigne le rôle d’acteur de la métamorphose qui se joue;
-   `obj`, qui désigne le rôle d’objet de la métamorphose qui se joue;
-   `auto`, qui désigne le cas où la divinité est à la fois actrice et objet d’une métamorphose, c’est-à-dire qu’elle se transforme elle-même, ce qui est cas courant chez les dieux;
-   `NA`, désigne les cas où le nom de la divinité est employé à des fins qui ne correspondent à aucun des cas cités précédemment.

Avec ces trois attributs, j’ai balisé 338 occurrences avec la balise `<persName>` sur l’ensemble des quinze livres des *Métamorphoses*.

### 1.1.3. Critères et limites méthodologiques

Le choix des critères a reposé sur mes questions directrices, mais aussi sur mon travail précédent. Dans la mesure où la délimitation des épisodes, des espaces de métamorphoses, des acteurs et des objets, pour ne citer que ces éléments, ont été réalisé l'année précédente, j’avais à ma disposition beaucoup d’éléments pour penser à un encodage plus direct dans le texte en vue d’une visualisation globale. Il s’agissait ici de croiser ces éléments déjà connus avec ceux, plus propres à la question du travail de mémoire, des mentions de divinités.

Le choix restreint des mentions de noms propres et périphrases, mais surtout de l’exclusion des pronoms de rappel et des pronoms adjectifs est principalement dû aux contraintes de temps. La recherche de cohérence et de clarté évoquée précédemment, le travail préalable sur les épisodes ainsi que l’existence préalable d’index des noms propres réduisaient les risques d'un oubli majeur potentiel. De plus, une partie de ma réflexion cherche à proposer une méthode de travail sur le texte, qui a pour vocation de s’étendre à d’autres divinités et à préciser les filtres de lecture à appliquer autant aux éléments choisis qu’à l’ensemble du texte.

Avant même de commencer à encoder le texte, grâce à un coup d'œil aux données et à travers les critères choisis, je m’attends à rencontrer une quantité importante de mentions d’acteurs hors des épisodes à proprement parler de métamorphoses. J'ai réalisé au cours de l'encodage de Minerve la nécessité d'une rigueur quant à l'encodage d'une divinité en tant qu'acteur dans un moment purement narratif. Le problème est résolu dès qu’il est possible d’établir un lien logique clair entre la mention de la divinité, qu’elle soit antérieure ou postérieure à la métamorphose directe, et l’épisode. Le lien logique est manifeste, que ce soit par l’emploi d’un pronom de rappel, d’un pronom adjectif, ou par la logique narrative de l’épisode. La mention encodée comme `act` est celle qui est la plus proche narrativement des vers de la métamorphose. \
Un cas simple pour illustrer cette situation est celui de Jupiter lorsqu’il transforme les fourmis d’Égine en hommes à la demande d'Éaque, au livre VII. La métamorphose est spécifiquement décrite dans les vers 639 à 642. Jupiter est mentionné depuis le début du passage narratif, que l’on considère commencer au vers 453 selon le fichier numérique, au vers 518 selon le découpage de Gilles Tronchet, et au vers 614 selon le découpage en épisodes de Georges Lafaye. Il est interpellé dans des contextes qui n’appellent pas de performance de sa part, et ces mentions sont dans ce cas rattachés à une fonction narrative. Ce n’est que sa mention au vers 627, dans une prière très précise d’Éaque concernant les fourmis (« *Totidem, pater optime, » dixit,/ « Tu mihi da ciues et inania moenia supple.* »)[^partie1-1] que la périphrase *pater optime* est encodée comme mention d’un acteur de la métamorphose qui se joue par la suite. À l’inverse, une de ses mentions précédentes, à savoir « *Iuppiter o!* » au vers 615, est elle encodée avec une analyse `NA`, car son invocation ici n’appelle ni ne provoque aucune métamorphose.

[^partie1-1]: « Tout ça, père tout puissant ! dis-je,/donne-moi autant d'habitants, remplis mes murs vides. » (trad. Marie Cosnay, 2017)

Ces décisions voient naître des difficultés et surtout créent des limites dans le processus de travail. La première difficulté réside dans la polymorphie des personnages divins : Minerve, Apollon et Jupiter peuvent apparaître sous forme d’allégorie, de divinité active, ou encore être nommés par divers épithètes. L’encodage vise à homogénéiser les occurrences pour chaque entité tout en préservant les niveaux d’interprétation offert par la richesse des apellations. Le choix des mentions encodées apporte une limite d’exhaustivité à un tel balayage du texte. Une seconde difficulté est celle du remplacement des mentions dans le contexte narratif. Comme évoqué dans l’exemple ci-dessus, les délimitations des épisodes sont différentes entre l'édition numérique, l’édition de Georges Lafaye et le travail de Gilles Tronchet, qui servent toutes des objectifs différents. Ainsi, replacer la mention dans un contexte narratif large, à l’échelle de l’épisode ou du sous-épisode est complexe entre éditions différentes. Le choix du contexte avec l’attribut `type` est basé sur le texte numérique croisé au découpage de Gilles Tronchet travaillé l'an passé. Ce choix s’est avéré le plus simple, bien qu’il pose des contraintes à la remise en contexte de la mention.

## 1.2. Méthodologies d'analyses

### 1.2.1 Analyse de répartition et approches quantitatives en humanités numériques

La première approhe numérique se veut d'abord globale : les premières observations à cette échelle sont celles des répartitions des divinités sur les quinze livres. L’analyse de répartition constitue une méthode exploratoire et descriptive, qui vise à cartographier la présence, la fonction et l’évolution des entités — ici, Minerve, Jupiter, Apollon — dans un corpus. Historiquement développée en linguistique de corpus, elle s’étend aujourd’hui aux humanités numériques pour suivre non seulement où apparaissent les entités, mais aussi comment et en quelles proportions. Les trois dimensions d'investigation sont les suivantes :

-   La répartition dans le texte : avec la fréquence et/ou la densité par livre et/ou segment narratif.
-   Le contexte narratif, à travers l’attribut `type`, qui replace la mention dans un contexte soit narratif soit de métamorphose.
-   La valeur interprétative, à travers l'attribut `ana`, qui permet de préciser le degré d’analyse interprétative grâce aux valeurs `act`, `obj`, `auto` ou `NA`).

La méthode s'appuie sur un encodage XML-TEI conforme aux standards @consortium_tei_nodate, reposant sur le marquage `<persName>` avec les trois attributs clés décrits en amont, à savoir `ref`, qui indique permet de regrouper les mentions sous la coupe d'une entité; `type`, qui décrit le cadre au sein de l’épisode ; et `ana`, qui indique l'annotation interprétative de la mention.

Voici un exemple d'une mention encodée au vers 563 du livre II des *Métamorphoses* :

\begin{center}
\texttt{<l n="563">redditur, ut dicar tutela pulsa <persName ref="MIN" type="narrative" ana="NA">Minervae</persName></l>}
\end{center}

Ce format permet de générer une base de données pour chaque occurrence, structurée selon l’unité narrative, en remontant à l'pisode et au livre, le type de moment dans l’unité narrative et le type d'intervention, selon la valeur d'`ana`. Cette systématisation ouvre la voie à des analyses croisées fines, par exemple par la comparaison du rôle et de la place dans le segment narratif, qui sont complexes si ce n’est impossible sans encodage standardisé.

### 1.2.2. Visualisation des répartitions : outils, formats et éclairages

Les données extraites des fichiers TEI sont converties en format tabulaire, puis traitées dans l’environnement R principalement à l’aide des *packages* `tidyverse` et `ggplot2`. Certains types de représentations graphiques sont privilégiées, chacun offrant un éclairage spécifique sur les dynamiques narratives et symboliques en jeu.

D’abord, des graphiques de répartition sont réalisés pour chaque livre. Ils visent à représenter la présence cumulative des divinités dans la structure linéaire du récit, afin d’en identifier les points de concentration, de dispersion ou d’absence. Ces visualisations permettent de repérer les moments d’intensification ou de retrait dans la narration divine. Ensuite, des graphiques de barres empilées sont régulièrement mobilisés pour visualiser la répartition des rôles associés à une même figure. Cette représentation permet de comparer les fonctions dominantes ou marginales que chaque divinité assume dans le texte, révélant des préférences narratives ou des variations selon les segments. Enfin, des matrices de co-occurrence croisant les annotations et le type d’intervention ou d’objet narratif sont représentées en *heatmap*. Ce type de visualisation permet de mettre en évidence les combinaisons sémantiques récurrentes, comme par exemple une possible conjonction fréquente ou épisodique entre `ana="act"` et `type="metamorphosis"`, qui signalerait des rôles actifs dans la dynamique des métamorphoses du texte.

L’ensemble de ces visualisations vise à constituer, pour chaque divinité, une représentation narrative articulant position dans le récit, fonction, et contexte d’intervention. Ce dispositif relève d’une approche de *data storytelling* narratif, telle que définie par Segel et Heer (@segel_narrative_2010), qui associe rigueur quantitative et lecture interprétative. Elle permet ainsi d’explorer la trajectoire des dieux et déesses dans le poème non seulement comme présence textuelle, mais aussi comme entité signifiante à part entière dans le récit ovidien.

## 1.3. Perspectives critiques et transdisciplinaires

L’analyse de répartition, même sans recourir à une modélisation en graphe, permet alors de caractériser quantitativement la présence narrative. Elle s’inscrit pleinement dans les approches macroscopiques des humanités numériques (@moretti_graphs_2007, p. 53)[^partie1-2] (@jockers_macroana_2_2013). Elle entre en dialogue avec  les analyses de trajectoire des personnages [@piper_enumerations_2018], l’étude de l’usage des noms propres dans les corpus et l’édition critique augmentée (@babeu_alison_rome_2011; @driscoll_digital_2016), où l’encodage TEI dynamise la critique textuelle. Cette méthode est particulièrement pertinente lorsque l’encodage des interactions est incomplet : elle valorise les attributs descriptifs (`ref`, `type`, `ana`), qui sont disponibles même en absence de liens explicites.

[^partie1-2]: “What do literary maps do ... First, they are a good way to prepare a text for analysis. You choose a unit-walks, lawsuits, luxury goods, whatever-find its occurrences, place them in space ... or in other words: you reduce the text to a few elements, and abstract them from the narrative fl.ow, and construct a new, artificial object like the maps that I have been discussing. And with a little luck, these maps will be more than the sum of their parts: they will possess 'emerging' qualities, which were not visible at the lower level.” @moretti_graphs_2007 p.53

### 1.3.1. Cadre technique et reproductibilité

L’exploitation des données encodées en XML-TEI repose sur un pipeline structuré, conçu pour extraire, analyser et visualiser les occurrences de divinités dans les *Métamorphoses* selon des critères narratifs et interprétatifs. Ce processus garantit la traçabilité des opérations et la reproductibilité scientifique de l’étude. La première étape consiste à parser les fichiers XML à l’aide de la fonction `read_xml()` du package `xml2` en environnement R. Combinée aux outils de la suite `tidyverse`, cette lecture permet d’extraire de manière ciblée les balises `<persName>` comportant les attributs structurants que `ref`, `type` et `ana`. Chaque balise est associée à son unité narrative de référence, qu’il s’agisse d’un livre, d’un épisode ou d’un segment temporel grâce à la numérotation interne.

Les données extraites sont alors organisées dans un *data frame* structuré, où chaque ligne correspond à une occurrence balisée, et chaque colonne à une variable analytique avec le nom de la figure (`ref`), le livre d’apparition, l'espace narratif (attribut`type`), et la valeur interprétative (`ana`). Cette tabularisation constitue une base stable pour les traitements statistiques et graphiques. Les visualisations sont générées en R à l’aide de `ggplot2` et des extensions adaptées.

Plusieurs types de représentations sont mobilisés pour rendre compte des différentes dimensions de l’analyse. Les fonctions `geom_col()`, `geom_point()` et `geom_line()` permettent de représenter de manière complémentaire la distribution des divinités dans la trame des *Métamorphoses*. Tandis que `geom_col()` traduit la fréquence relative ou absolue des mentions dans chaque livre sous forme de barres verticales, facilitant ainsi l’identification des zones de concentration narrative, `geom_point()` permet de visualiser ces occurrences comme des points discrets, positionnés en fonction d’un repère temporel ou structurel (dans notre étude ici, le numéro de livre). Cette représentation ponctuelle offre une lecture plus fine et granulaire de la répartition. L'utilisation de `geom_line()`, qui relie les points entre eux, fait émerger une dynamique continue, révélant des tendances ou des progressions narratives dans l’apparition des divinités. L’ensemble de ces visualisations contribue ainsi à une lecture à la fois quantitative et qualitative du rôle des figures divines. Les relations croisées entre les attributs sont visualisées via ces paramètres de visualisaiton, mais également dans une matrices de co-occurrence construite avec `geom_tile()` (*heatmaps*) permettant d’identifier des motifs interprétatifs dominants ou des asymétries symboliques.

Ces visualisations, loin d’être purement descriptives, constituent un support essentiel pour l’interprétation scientifique. Elles autorisent des comparaisons inter-divinités (que je ne mets pas en place ici), la détection de ruptures narratives ou d’évolutions dans les représentations, et la mise en évidence de configurations singulières dans l’usage des figures mythologiques. Ce pipeline analytique est accesible dans plusieurs fichiers .R ponctués de commenaires suivant les différntes étapes de lecture, extraction, nettoyage, structuration, visualisation etinterprétation. Cette approche garantit la transparence méthodologique et la répétabilité des résultats, conformément aux standards des humanités numériques. Les scritps d’analyse R sont archivés dans [le dépôt de données Git Hub](https://github.com/pax3l/m2_ovid_deities_analysis_for_quarto) en vue de toute reproductibilité, amélioration et observation de l'encodage.

### 1.3.2. Navigation dans le texte et exploration personnelle des données : l’édition électronique (EVT)

<!--(lien encore non présent!)-->

Afin d’ancrer les données issues de l’analyse computationnelle dans le texte littéraire lui-même et autoriser une exploration plus individuelle des données, une édition électronique enrichie a été créée avec l’outil EVT (Edition Visualization Technology). Il s’agit d’une interface web qui permet de consulter le texte encodé (au format TEI-XML), avec un système de navigation par entités et références croisées.

L’interface donne accès à :

-   Une lecture du texte latin et des annotations des divinités, permettant de suivre à la fois la version originale et d’avoir à la loupe les objets d’étude ;

-   Un index dynamique des personnages encodés, qui permet de filtrer le texte par entité et d’explorer ses différentes occurrences ;

-   Des cartes de réseau interactives, affichables par livre ou épisode, qui sont directement reliées au texte encodé, assurant ainsi la traçabilité des données ;

-   Des filtres permettant de suivre un personnage dans l’ensemble de l’œuvre, par exemple pour reconstituer la trajectoire de Minerve ou identifier tous les récits où Jupiter intervient en tant qu’acteur de métamorphose.

Cette édition vise une double finalité : offrir un outil d’analyse au chercheur (grâce aux liens avec les données quantitatives) et rendre le résultat intelligible à un lectorat plus large (enseignants, étudiants, passionnés de littérature antique). Le dialogue entre quantité et qualité, *distant reading* et *close reading*, trouve ici une expression concrète. Enfin, cette interface est reliée au dépôt GitHub du dossier du mémoire à travers son fichier [Read.md](https://github.com/pax3l/m2_ovid_deities_analysis_for_quarto/blob/main/README.md). Cette accessibilité vise encore ici à la reproductibilité scientifique du travail et encourage une approche collaborative de la recherche en humanités numériques. \
\
Ces méthodes d'analyse ont pour objectif de dresser des profils qualitatifs plus précis des divinités à la lumière des données quantitatives, et de comprendre les schémas narratifs dans lesquels elles s’insèrent. L’analyse des répartitions ouvre alors sur une interprétation qualitative et littéraire, qui sera développée dans les parties suivantes.

## 1.4. Minerve, Apollon, Jupiter : premiers portraits

L'analyse moderne des représentations divines en littérature antique est prend comme base de travail des corpus inégaux. Elle est très souvent recoupée avec l’analyse des rites, des représentations visuelles, souvent statuaires, qui sont au cœur de la pratique des grecs et des romains dans leur rapport aux divinités. Les caractéristiques et attributs de ces divinités se transmettent de façon toujours déclinées mais très similaires depuis la Grèce archaïque jusqu’à la Rome impériale. Dans le contexte de l'Empire romain, les divinités occupent une place à la fois symbolique, morale et culturelle. Elles incarnent des principes abstraits, des forces naturelles ou bien des idéaux civiques, tout en restant des figures mythologiques au cœur du récit poétique et philosophique. Les auteurs latins oscillent entre un traitement narratif traditionnel, comme Virgile dans l’*Énéïde* et Ovide lui-même, et une réflexion philosophique sur la nature divine. Ces divinités incarnent des valeurs motrices ou disruptives de la société romaine — sagesse, justice, vengeance, guerre — et justifient ainsi l’ordre du monde, en expliquant des situations politiques ou interrogeant la condition humaine. D’autres auteurs, tels que Cicéron dans le *De Natura Deorum*, ont une approche bien plus critique et rationaliste, et invitent à une lecture plus philosophique de leur existence. Le paysage littéraire confère donc aux divinités une double facette qui témoigne d’une transition dans la population, entre appropriation du patrimoine religieux, hérité de la Grèce antique, et outil d’expression culturel et intellectuel. Cette phase de transition invite à examiner leurs diverses représentations et les différences notables entre les auteurs. Les différentes époques construisent des portraits aux légères variations des divinités, dont les auteurs se sont fait porteurs de la tradition pour leurs successeurs. Il ne s'agit pas ici à construire un portrait exhaustif comparé entre les auteurs des figures de divinités. Il s'agit plutôt ici de dresser un portrait non exhaustif soulignant les caractéristiques principales des figures divines chez des auteurs contemporains d'Ovide, afin d’avoir un point de départ et de comparaison avec les éléments apportés par l’analyse numérique.

Bien que chaque auteur maintienne un rapport personnel au passage de la République à l’Empire, à Auguste et à la politique de Rome en général, il est de mise de postuler que les divinités ne sont pas traitées de façon totalement opposées d’une époque à l’autre, particulièrement celle qui sont choisies pour cette étude, et que leur portrait s’inscrit dans un ensemble de codes, présents également hors littérature, qui forment une image continue.

Le cadre littéraire est donc celui des auteurs contemporains d’Ovide, qui participent à l’établissement de l’image des divinités dans la littérature latine de l’époque classique et impériale. Parmi eux, Virgile, inspiration presque explicite pour de nombreux évènements des *Métamorphoses*. On observe aussi les textes des contemporains évidents d'Ovide, tels que Tite-Live, Horace, et Sénèque l’Ancien, malgré un genre littéraire de prédilection différent. Les contemporains également liés par le style élégiaque ne sont occultés, tels Horace et Tibulle, ce dernier attestant d’une relation directe avec Ovide dans les textes. L’établissement des portraits est réalisé grâce à des recherches des patronymes latins les plus courants dans les bases de données de la Perseus Digital Library, dans le nouvel environnement de lecture [Scaife Viewer](#0).

### 1.4.1. Apollon, amoureux transit des arts et des mortels

Le *Dictionnaire des noms des divinités* de Michel Mathieu-Colas[@mathieu-colas_dictionnaire_nodate] propose une description d’Apollon comme le « dieu de la lumière de la beauté et des arts ». Ses variations Phoebus et Phébus le lient plus explicitement au Soleil. On retrouve directement des mentions du Soleil, Hélios, dans des récits de toute nature, cosmogoniques (*Théogonie*) ou encore pastoraux (*Les Bucoliques*), mais aussi dans des cadres épiques, des contextes de guerre ou de conflits. Apollon y est alors associé à la Pythie, sa dévouée prêtresse au temple de Delphes, connue pour ses oracles décisifs mais souvent sibyllins. Tite-Live, dans un contexte plus historique, le mentionne surtout ce cadre, ou en tous cas dans un contexte religieux ou rituel (*itaque inde consules, ne criminationi locus esset, in prata Flaminia, ubi nunc aedes Apollinis est — iam Apollinare appellabant — , avocavere senatum*)[^partie1-3]. Les auteurs élégiaques le nomment, sans trop de surprise, surtout dans des appels à la protection, à la consécration des arts et à l’inspiration, à côté des Muses. Son rôle est principalement celui d’une divinité protectrice et d’un oracle de référence.

[^partie1-3]: *Ab urbe condita*, III, 63.7 : *«* Les consuls, pour ôter tout prétexte à ces plaintes, transférèrent l'assemblée dans les prés Flaminiens, où l'on voit aujourd'hui le temple, et où se trouvait déjà alors le domaine d'Apollon. » (trad. Philippe Remacle)

### 1.4.2. Minerve, stratège fière, protectrice des techniques

Elle est désignée dans le même dicitonnaire[@mathieu-colas_dictionnaire_nodate], sous son avatar le plus simple comme la « déesse de la pensée, des lettres et des arts; protectrice des corporations et des métiers ». Sa variante grec, Athéna, y ajoute « des sciences ». Ses occurrences ne sont pas très nombreuses chez les contemporains d’Ovide. Elle semble régulièrement mentionnée parmi d’autres divinités, en description de lieux lui rendant hommage, ou invoquée dans un appel à la protection des arts, aux lettres, à la raison. Dans l’hymne homérique à Athéna, c’est son caractère de protectrice de la ville, et ses capacités guerrières qui sont soulignées, avec un parallèle à Arès. Chez Virgile, elle est invoqué à travers les caractéristiques précédemment évoquées dans le passage qui mène à la construction des armes d’Énée par Vulcain, d’abord simplement pour évoquer les travaux manuels des femmes (*cui tolerare colo uitam tenuique Minerua/impositum,* […], 8, 409-410)[^partie1-4], puis pour insister sur son caractère guerrier à travers le rappel de son histoire avec la Gorgone (*aegidaque horriferam, turbatae Palladis arma,/certatim squamis serpentum auroque polibant/conexosque anguis ipsamque in pectore diuae/Gorgona, desecto uertentem lumina collo.*)[^partie1-5]. Les autres auteurs élégiaques la mentionnent peu, et de façon peu significative. Tite-Live la mentionne dans au moins 20 passages différents du *Ab urbe condita*, souvent à côté d’une mention de Jupiter. Elle y est présentée comme la déesse des nombres (*eum clavum, quia rarae per ea tempora litterae erant, notam numeri annorum fuisse ferunt eoque Minervae templo dicatam legem, quia numerus Minervae sit.*)[^partie1-6], mais le plus souvent associée à la triade capitoline, avec Jupiter et Junon, et dans le cadre de mentions à des rites, des offrandes ou des sacrifices, notamment à l'évocation des Quinquatries au livre XXVII. La déesse, dans un ensemble de mentions qui prennent peu le temps de la description, se présente comme gardienne des techniques, des sujets de pensée, et accessoirement renfort de la stratégie guerrière.

[^partie1-4]: *Énéide*, 8, 409-410 : « \[c'était l'heure où la femme\] qui n'a pour soutenir sa vie que ses fuseaux et les délicats travaux de Minerve, \[…\] » (trad. A. Desportes)

[^partie1-5]: *Énéide*, 8, 435-438 : « l'égide dont s'arme Pallas en fureur; horrible armure où se montrent des serpents aux écailles d'or et des couleuvres entrelacées; et, pour le sein même de la déesse, une Gorgone dont la tête coupée lançait encore d'affreux regards. » (trad. A. Desportes)

[^partie1-6]: *Ab urbe condita* 7.3.6 : « Ce clou, dans ces temps où l'écriture était si rare, marquait, dit-on, le nombre des années: et la loi fut ainsi consacrée dans le sanctuaire de Minerve, parce que Minerve avait inventé les nombres. » (trad. Philippe Remacle)

### 1.4.3. Jupiter, amant invétéré, père des dieux et des hommes

Jupiter, dans sa forme latine la plus simple, est décrit par Mathieu-Colas[@mathieu-colas_dictionnaire_nodate] comme le « dieu du Ciel, de la lumière, de la foudre, père et souverain des dieux ». Chez Ovide, il prend ses racines dans le Zeus de l'*Énéide* de Virgile et celui de l'Iliade et l’Odyssée d’Homère, mêlant un autoritarisme solennel et une puissance capricieuse, tantôt bienveillante tantôt destructrice. Le contexte littéraire mais surtout politique d’Ovide lui fait prendre une position plus importante, puisqu’il fait de Jupiter le pendant divin d’Auguste, ce qui est explicitement lisible au livre XV (858–860) :

> *Iuppiter arces*<br> *temperat aetherias et mundi regna triformis*<br> *terra sub Augusto est; pater est et rector uterque.*[^partie1-7]

[^partie1-7]: *Métamorphoses* 15, 858–860, trad. de @bakhouche_larchitecture_2019 : « Jupiter règne dans le ciel, la terre obéit à Auguste: tous deux sont les pères et les souverains de leur empire ».

Jupiter a fait l’objet d’une analyse très récente dans les œuvres principales d’Ovide, ce qui n’est pas le cas dans la bibliographie accessible sur Minerve et Apollon. Dans son article « Jupiter in Ovid’s Metamorphoses » Charles @segal_jupiter_2025 propose un portrait de Jupiter dans les *Métamorphoses* à partir de l’héritage antique de Virgile et Homère, en faisant des parallèle avec des auteurs contemporains d’Ovide. Jupiter est alors d’abord « le gardien responsable de l’ordre humain et divin » (p. 79). Il se caractérise principalement par la colère et la violence (p.80), moteurs principaux des métamorphoses qu’il provoque. Il incarne une ambivalence, entre un père colérique et tout-puissant, et un mari trompeur, craintif des représailles de sa femme. Malgré sa toute-puissance et son commandement sur l’ensemble des dieux et des hommes, sur lesquels il n’hésite pas à abattre son courroux, il ploie devant le regard de Junon et sa colère face à ses infidélités. Un coup d'œil à l’*index nominum* permet de confirmer qu’il est le dieu le plus mentionné dans l’ensemble des livres. Son rôle narratif et symbolique chez Ovide est souligné par Ségal, pour qui « Ovid's ways of treating the Olympian ruler self-consciously embodies the contrasting thematic and stylistic levels of the poem. » (p.83)[^partie1-8].

[^partie1-8]: Les moyens qu’Ovide emploie pour traiter du souverain de l’Olympe incarnent consciemment les thèmes contrastés et les niveaux de style du poème. placer la citation en notes. (trad. personnelle*)*

Cette première partie a permis d'établir les fondations méthodologiques nécessaires à une analyse numérique des divinités dans les Métamorphoses d'Ovide. En s'appuyant sur le travail d'encodage XML-TEI préalablement réalisé par Nadine Rakofsky, j'ai développé un protocole d'analyse personnel qui conjugue rigueur philologique et outils numériques. L'encodage de 338 occurrences à travers les quinze livres, organisé autour de trois attributs structurants, constitue désormais une base de données exploitable pour l'analyse quantitative. Cette systématisation permet de dépasser les approches traditionnelles, souvent fragmentaires, de l'étude des divinités ovidiennes. Les choix méthodologiques opérés — limitation aux noms propres et périphrases, distinction entre contexte narratif et métamorphique, typologie des rôles actantiels — offrent un cadre d'analyse reproductible et extensible à d'autres figures divines.

Les premiers portraits établis révèlent déjà des spécificités intéressantes : Minerve apparaît comme une figure stratégique, protectrice des techniques ; Apollon se dessine en divinité des arts et un oracle de référence ; Jupiter s'impose comme la figure paternelle ambivalente, oscillant entre autorité souveraine et vulnérabilité conjugale. Ces caractérisations, issues des sources antiques et de la critique moderne, constituent notre socle interprétatif. L'infrastructure technique mise en place — pipeline d'extraction R, visualisations dynamiques, édition électronique EVT — garantit non seulement la reproductibilité scientifique de notre démarche, mais ouvre également des perspectives de recherche collaborative. Cette approche méthodologique représente un apport significatif à l'étude de ce texte d'Ovide, en proposant une entrée différentes aux approches des lectures traditionnelles.

Les fondations étant posées, il convient désormais de mettre à l'épreuve notre dispositif d'analyse. Les données encodées dévoilent maintenant leurs potentialités heuristiques à travers l'exploration systématique des répartitions, des fréquences et des contextes d'apparition de nos trois divinités. La partie suivante procédera d'abord à une analyse structurelle globale, en établissant les profils quantitatifs de Minerve, Apollon et Jupiter les *Métamorphoses*. Cette exploration révélera les logiques de distribution narrative, les corrélations entre interventions divines et segments textuels, ainsi que les schémas récurrents qui structurent le récit ovidien grâce à des visualisations spécialisées. L'enjeu de cette exploration des données est double : valider empiriquement les portraits divins esquissés et identifier les structures quantitatives qui orienteront l'interprétation littéraire. Les résultats obtenus alimenteront directement la troisième partie, consacrée à la relecture critique des portraits divins et à l'analyse approfondie d'épisodes emblématiques, où données et interprétations dialogueront pour révéler ce que l'approche numérique apporte à la compréhension des *Métamorphoses*.
